# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e88e11dfb28b4dc2cc447c1f40e2659ae5ffe2d080aca15bcbe18902182e123d3b348356acbc1223e8e8c18e93dec19acf9a4ef19a80e93818494181d36a1775

test:
  secret_key_base: 01410cac260a252f418f25be37f6d2eee6d11349615b874e9c40d8a09368428e7ac4b3d3acbc2fc7eb6d40893fa39cf3a34ee48308deacc028a9e3febc562276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
